server.port=8081
logging.file.name=/var/log/logapp/application.log
logging.level.root=INFO

# Actuator - secure default (only health endpoint)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
